name: Ruby

on: [push]

jobs:
  run_spec:
    name: Rspec

    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: mysql123
      container:
        image: ruby:2.5.1
        env:
          DATABASE_URL: mysql2://root:mysql123@mysql:3306/rails6_sample

    steps:
      # actions/checkoutリポジトリのaction.ymlを利用する
      - uses: actions/checkout@v1 # https://github.com/actions/checkout/blob/master/action.yml
      - name: Build and setup
        run: |
          rm -f config/database.yml
          gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
          bundle config set deployment 'true'
          bundle install --jobs 4 --retry 3
          bundle exec rails db:setup assets:precompile
      - name: Exec tests
        run: bundle exec rspec
