name: Ruby

on:
  push:
    paths-ignore:
      - README.md
      - docs/**
      - Dockerfile
      - docker-compose.yml
jobs:
  run_spec:
    name: Rspec

    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_TEST_PORT: 33060
      # 以下、ダミー変数
      DATABASE_URL: 127.0.0.1
    services:
      db:
        image: mysql:5.7.27
        ports:
          - 33060:3306
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          BIND-ADDRESS: 0.0.0.0
    #container:
      #image: ruby:2.6.3
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: apt-get
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev
    - name: Cache gems
      uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Cache node modules
      uses: actions/cache@preview
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: bundle install
      run: |
        gem install bundler:1.16.6
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: yarn install
      run:  yarn install --check-files
    - name: migration
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
    - name: run rspec
      run: bundle exec rspec
